=== ShoresForgotten/WebHypno/src/schemas/glshader.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "urn:shoresforgotten:hypnoweb:schemas:glshader:v1",
    "title": "Fullscreen Fragment Shader Information (WebGL)",
    "descripton": "A description of the uniforms that form the interface of a fullscreen shader",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the shader, to be displayed to the user",
            "type": "string"
        },
        "fileName": {
            "descripton": "The file that contains the shader in question (currently has to be located in the same directory",
            "type": "string"
        },
        "time": {
            "description": "The name of the uniform that keeps track of time",
            "type": "string"
        },
        "resolution": {
            "description": "The name of the uniform that describes the resolution of the screen",
            "type": "string"
        },
        "debugOnly": {
            "description": "Whether or not this shader should only appear in debug mode",
            "type": "boolean"
        },
        "uniforms": {
            "descripton": "The information about the uniforms themselves",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "description": "The type of the uniform",
                        "type": "string"
                    },
                    "name": {
                        "description": "The name of the setting to display to the user",
                        "type": "string"
                    },
                    "settings": {
                        "description": "USE ONLY WITH TYPE multi; for grouping uniforms",
                        "type": "array",
                        "items": {
							"type": "object",
                            "properties": {
								"type": {
									"description": "The type of the uniform",
									"type": "string"
								},
								"name": {
									"description": "The name of the setting to display to the user",
									"type": "string"
								},
								"accessor": {
									"descripton": "The string that identifies the uniform location",
									"type": "string"
								},
								"min": {
									"description": "USE ONLY WITH NUMERIC TYPES; The minimum value of this uniform",
									"type": ["integer", "number"]
								},
								"max": {
									"description": "USE ONLY WITH NUMERIC TYPES; The maximum value of this uniform",
									"type": ["integer", "number"]
								},
								"init": {
									"description": "The initial value of this uniform",
									"type": ["integer", "number", "string"]
								}
							},
							"required": ["type", "name", "accessor", "init"]
                        }
                    },
                    "accessor": {
                        "descripton": "The string that identifies the uniform location",
                        "type": "string"
                    },
                    "min": {
                        "description": "USE ONLY WITH NUMERIC TYPES; The minimum value of this uniform",
                        "type": ["integer", "number"]
                    },
                    "max": {
                        "description": "USE ONLY WITH NUMERIC TYPES; The maximum value of this uniform",
                        "type": ["integer", "number"]
                    },
                    "init": {
                        "description": "The initial value of this uniform",
                        "type": ["integer", "number", "string"]
                    }
                },
				"required": ["type", "name"]
            }
        }
    },
    "required": ["name", "fileName", "debugOnly", "uniforms"]
}

=== ShoresForgotten/WebHypno/src/shaders/webgl/spiral.frag.json
{
    "name": "Spiral",
    "fileName": "spiral.frag",
    "time": "iTime",
    "resolution": "iResolution",
    "debugOnly": false,
    "uniforms": [
        {
            "type": "int",
            "name": "Arm count",
            "accessor": "arms",
            "min": 1,
            "init": 10
        },
        {
            "type": "float",
            "name": "Zoom level",
            "accessor": "zoom",
            "init": 0.5
        },
        {
            "type": "float",
            "name": "Rotation speed",
            "accessor": "speed",
            "init": 1.0
        },
        {
            "type": "multi",
            "name": "Arm one",
            "settings": [
                {
                    "type": "color",
                    "name": "Arm one color",
                    "accessor": "colors[0]",
                    "init": "000000"
                },
                {
                    "type": "float",
                    "name": "Arm one size",
                    "accessor": "sizes[0]",
                    "min": 0.01,
                    "init": 1.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Arm two",
            "settings": [
                {
                    "type": "color",
                    "name": "Arm two color",
                    "accessor": "colors[1]",
                    "init": "FFFFFF"
                },
                {
                    "type": "float",
                    "name": "Arm two size",
                    "accessor": "sizes[1]",
                    "min": 0.01,
                    "init": 1.0
                }
            ]
        }
    ]
}

=== ShoresForgotten/WebHypno/src/shaders/webgl/2ring.frag.json
{
    "name": "Two Colored Rings",
    "fileName": "2ring.frag",
    "time": "iTime",
    "resolution": "iResolution",
    "debugOnly": false,
    "uniforms": [
        {
            "type": "float",
            "name": "Zoom",
            "accessor": "zoom",
            "init": 1.0,
            "min": 0.01
        },
        {
            "type": "float",
            "name": "Speed",
            "accessor": "speed",
            "init": -0.1
        },
        {
            "type": "multi",
            "name": "Ring One",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring One Color",
                    "accessor": "colors[0]",
                    "init": "000000"
                },
                {
                    "type": "float",
                    "name": "Ring One Size",
                    "accessor": "sizes[0]",
                    "init": 1.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Two",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Two Color",
                    "accessor": "colors[1]",
                    "init": "FFFFFF"
                },
                {
                    "type": "float",
                    "name": "Ring Two Size",
                    "accessor": "sizes[1]",
                    "init": 1.0,
                    "min": 0.0
                }
            ]
        }
    ]
}

=== ShoresForgotten/WebHypno/src/shaders/webgl/radial_fade.frag.json
{
    "name": "Radial Fade",
    "fileName": "radial_fade.frag",
    "time": "iTime",
    "resolution": "iResolution",
    "debugOnly": false,
    "uniforms": [
        {
            "type": "color",
            "name": "Color One",
            "accessor": "colors[0]",
            "init": "FF00FF"
        },
        {
            "type": "color",
            "name": "Color Two",
            "accessor": "colors[1]",
            "init": "000000"
        }
    ]
}

=== ShoresForgotten/WebHypno/src/shaders/webgl/6ring.frag.json
{
    "name": "Six Colored Rings",
    "fileName": "6ring.frag",
    "time": "iTime",
    "resolution": "iResolution",
    "debugOnly": false,
    "uniforms": [
        {
            "type": "float",
            "name": "Zoom",
            "accessor": "zoom",
            "init": 1.0,
            "min": 0.01
        },
        {
            "type": "float",
            "name": "Speed",
            "accessor": "speed",
            "init": -0.1
        },
        {
            "type": "multi",
            "name": "Ring One",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring One Color",
                    "accessor": "colors[0]",
                    "init": "000000"
                },
                {
                    "type": "float",
                    "name": "Ring One Size",
                    "accessor": "sizes[0]",
                    "init": 20.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Two",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Two Color",
                    "accessor": "colors[1]",
                    "init": "76A420"
                },
                {
                    "type": "float",
                    "name": "Ring Two Size",
                    "accessor": "sizes[1]",
                    "init": 20.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Three",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Three Color",
                    "accessor": "colors[2]",
                    "init": "000000"
                },
                {
                    "type": "float",
                    "name": "Ring Three Size",
                    "accessor": "sizes[2]",
                    "init": 1.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Four",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Four Color",
                    "accessor": "colors[3]",
                    "init": "669BE1"
                },
                {
                    "type": "float",
                    "name": "Ring Four Size",
                    "accessor": "sizes[3]",
                    "init": 20.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Five",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Five Color",
                    "accessor": "colors[4]",
                    "init": "000000"
                },
                {
                    "type": "float",
                    "name": "Ring Five Size",
                    "accessor": "sizes[4]",
                    "init": 1.0,
                    "min": 0.0
                }
            ]
        },
        {
            "type": "multi",
            "name": "Ring Six",
            "settings": [
                {
                    "type": "color",
                    "name": "Ring Six Color",
                    "accessor": "colors[5]",
                    "init": "04BAAD"
                },
                {
                    "type": "float",
                    "name": "Ring Six Size",
                    "accessor": "sizes[5]",
                    "init": 20.0,
                    "min": 0.0
                }
            ]
        }
    ]
}

=== ShoresForgotten/WebHypno/src/shaders/webgl/test.frag.json
{
    "name": "Debug shader",
    "fileName": "test.frag",
    "time": "iTime",
    "resolution": "iResolution",
    "debugOnly": true,
    "uniforms": [
        {
            "type": "color",
            "name": "Colour (UK English)",
            "accessor": "colorOne",
            "init": "FF00FF"
        },
        {
            "type": "float",
            "name": "Dingus",
            "accessor": "dingus",
            "init": 1.0
        }
    ]
}
